from bs4 import BeautifulSoup


# soup = BeautifulSoup('<b class="boldest">Extremely bold</b>', 'html.parser')
# tag = soup.b
# print(tag)
# <class 'bs4.element.Tag'>

# most important tag's methods
# print(tag.name)
# tag.name = 'div'  # it will reflected in any markup generated by BeautifulSoup
# print(tag.name)
# print(tag)

# tag = BeautifulSoup('<b id="boldest">bold</b>', 'html.parser').b  # check the tail of expression
# print(tag['id'])  # attributes are accessed in a way dictinaries are
# # 'boldest'
# # another way of access attributes
# print(tag.attrs['id'])


# You can add, remove, and modify a tag’s attributes. Again, this is done by treating the tag as a dictionary:
tag = BeautifulSoup('<b id="boldest">bold</b>', 'html.parser').b
tag['id'] = 'verybold'
tag['another-attribute'] = 1
print(tag)

del tag['id']
del tag['another-attribute']
print(tag)
